### ISSUE TITLE
TimeZones

### ISSUE THREAD

**Issue by joshn-ridewta-com** [joshn-ridewta-com/PoshIssues#31]
The current Status Date/Time records the date/time in the timezone where the status is updated without appending timezone.  The time should be tracked via GMT and then displayed in local time.

**Comment by joshnylander** [comment]
Also scheduledAfter

**Comment by joshnylander** [comment]
Use UTC, see https://docs.microsoft.com/en-us/dotnet/standard/datetime/converting-between-time-zones
