### ISSUE TITLE
Date handling of legacy fix objects

### ISSUE THREAD

**Issue by joshnylander** [joshn-ridewta-com/PoshIssues#47]
There is either a bug or improper handling of legacy (pre-UTC) date properties in the Read-IssueFix cmdlet, or both.

**Comment by joshn-ridewta-com** [comment]
Found a bug in date handling, not going to fix legacy objects.  v1 is a breaking change.  But I did fix bugs in Read and Write cmdlets.  Now v1.0.1

**Comment by joshn-ridewta-com** [comment]
Found additional bugs in New-IssueFix where I did not account for the new UTC naming of properties.

**Comment by joshn-ridewta-com** [comment]
This is not an issue moving forward.
